project:
  type: website
  output-dir: docs

website:
  title: "Tipologi Kerentanan Perdesaan"
  navbar:
    left:
      - href: tipologi_wilayah_sumsel.qmd
        text: Sumsel
      - href: tipologi_wilayah_banyuasin.qmd
        text: Banyuasin

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
